# GitHub Action: run unit tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
